fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: check-xml
      - id: check-toml
      - id: check-yaml
      - id: check-ast
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff
        args: [ --fix, --config, pyproject.toml ]
      - id: ruff-format
  - repo: https://github.com/PyCQA/bandit
    rev:  1.8.6
    hooks:
      - id: bandit
        args: [-c, "pyproject.toml"]
        additional_dependencies: [ "bandit[toml]" ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies:
          - django-stubs
