name: Publish to PyPI

on:
  release:
    types: [ published ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install Python 3.11
        run: uv python install 3.11

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish
